name: Deploy Website
on:
  workflow_dispatch
jobs:
  get-jobs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Moving to packages/jobboard/website folder
      run: cd packages/jobboard/website
    - name: Installing npm packages
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
    - name: Building production
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: build
    - name: Get new jobs posts
      uses: crocoder-dev/serverless-github-action@master
      with:
        command: 'deploy'
