name: Deploy Scrapper
on:
  workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Moving to packages/jobboard/scrapper folder
      run: cd packages/jobboard/scrapper
    - name: Node setup
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Installing npm packages
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
    - name: Serverless deploy
      uses: crocoder-dev/serverless-github-action@master
      with:
        command: 'deploy'
