name: Publish Components
on:
  workflow_dispatch
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Node setup
      uses: actions/setup-node@v1
      with:
        node-version: 12
        registry: https://npm.pkg.github.com/
    - run: cd packages/components && yarn install
    - run: cd packages/components && yarn build
    - run: "cd packages/components && PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]') && yarn publish --new-version $PACKAGE_VERSION"
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GIT_TOKEN }}
